version: "3.7"

services:

  # nginx:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-sample
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    networks:
      - sample-network

  # php
  php81-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php81-sample
    ports:
      - "9001:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - sample-network

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-sample
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: db-user
      MYSQL_PASSWORD: secret
    networks:
      - sample-network

networks:
  sample-network:
